on:
  schedule:
    - cron: '*/5 * * * *' # Runs every day at midnight


jobs:
  hello_world:
    runs_on: ubuntu-latest
    steps:
      - name: Echo Current Date and Time
        run: echo "Current date and time: $(date)"
        